### ISSUE TITLE
Support for python 3.11

### ISSUE THREAD

**Issue by dimarkov** [google/array_record#49]
Hi a support for python 3.11 would be great. Currently, new version of tensorflow_datasets cannot be run with python 3.11 because array_record is not compiled to support that.

**Comment by cdeepali** [comment]
I am able to install the [array_record-0.4.1-py310-none-any.whl](https://files.pythonhosted.org/packages/93/8e/c6b646029a9c544ecd6806c6ea0efb67d0ba3300e1d68518f58d9774d3f0/array_record-0.4.1-py310-none-any.whl) in py311 env and `import array_record` works. 

Does that mean that the py310 .whl is compatible with py311 as well?

**Comment by jamesmyatt** [comment]
0.5.0 has python 311 wheels: https://pypi.org/project/array-record/0.5.0/#files

**Comment by NeilGirdhar** [comment]
(But no 3.12 wheel?)
