### ISSUE TITLE
Release wheels for Python 3.12

### ISSUE THREAD

**Issue by NeilGirdhar** [google/array_record#94]
This blocks tensorflow-datasets on Python 3.12 from being installed. Is there any way to get the wheels released?

**Comment by romanngg** [comment]
+1, this also blocks our library from supporting Python 3.12.

**Comment by marcenacp** [comment]
I now see [builds](https://pypi.org/project/array-record/#files) for Python 3.12, so I'll mark this issue as fixed. Feel free to reopen if the problem persists!
